app-symfony/src/Entity/Purchase.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Employee;
use App\Entity\Timeslot;
use App\Entity\User;
use Exception;

/**
 * Purchase
 *
 * @ORM\Table(name="purchase", indexes={@ORM\Index(name="idEmployee", columns={"idEmployee"}), @ORM\Index(name="idTimeslot", columns={"idTimeslot"}), @ORM\Index(name="idUser", columns={"idUser"})})
 * @ORM\Entity(repositoryClass="App\Repository\PurchaseRepository")
 */
class Purchase
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateCreation", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $datecreation = 'CURRENT_TIMESTAMP';

    public const STATUSES = [
        0 => 'CREATED',
        1 => 'PREPARED',
        2 => 'CANCELED'
    ];

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer", nullable=false)
     */
    private $status;

    /**
     * @var int
     *
     * @ORM\Column(name="amount", type="integer", nullable=false)
     */
    private $amount;

    /**
     * @var int
     *
     * @ORM\Column(name="toPay", type="integer")
     */
    private $toPay;

    /**
     * @var int
     *
     * @ORM\Column(name="itemsNumber", type="integer", nullable=false)
     */
    private $itemsNumber;

    /**
     * @var int
     *
     * @ORM\Column(name="missingNumber", type="integer", nullable=false)
     */
    private $missingNumber;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idUser", referencedColumnName="id")
     * })
     */
    private $user;

    /**
     * @var Employee
     *
     * @ORM\ManyToOne(targetEntity="Employee")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idEmployee", referencedColumnName="id")
     * })
     */
    private $employee;

    /**
     * @var Timeslot
     *
     * @ORM\ManyToOne(targetEntity="Timeslot")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idTimeslot", referencedColumnName="id")
     * })
     */
    private $timeSlot;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Product", inversedBy="idorder")
     * @ORM\JoinTable(name="order_detail",
     *   joinColumns={
     *     @ORM\JoinColumn(name="idOrder", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="idProduct", referencedColumnName="id")
     *   }
     * )
     */
    private $products;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="Purchasedetail", mappedBy="purchase")
     */
    private $orderDetails;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatecreation(): ?\DateTimeInterface
    {
        return $this->datecreation;
    }

    public function setDatecreation(\DateTimeInterface $datecreation): self
    {
        $this->datecreation = $datecreation;

        return $this;
    }

    public function getStatusKey(): ?int
    {
        return 0; // TODOS
    }

    public function getStatusLabel(): ?string
    {
        return self::STATUSES[$this->status];
    }

    public function setStatus(int $status): self
    {
        if (array_key_exists($status, self::STATUSES)) {
            $this->status = $status;
            return $this;
        } else {
            throw new Exception("This status doesn't exists !");
        }
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getToPay(): ?int
    {
        return $this->toPay;
    }

    public function setToPay(int $toPay): self
    {
        $this->toPay = $toPay;

        return $this;
    }

    public function getItemsNumber(): ?int
    {
        return $this->itemsNumber;
    }

    public function setItemsNumber(int $itemsNumber): self
    {
        $this->itemsNumber = $itemsNumber;

        return $this;
    }

    public function getMissingNumber(): ?int
    {
        return $this->missingNumber;
    }

    public function setMissingNumber(int $missingNumber): self
    {
        $this->missingNumber = $missingNumber;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): self
    {
        $this->employee = $employee;

        return $this;
    }

    public function getTimeSlot(): ?Timeslot
    {
        return $this->timeSlot;
    }

    public function setTimeSlot(?Timeslot $timeSlot): self
    {
        $this->timeSlot = $timeSlot;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        $this->products->removeElement($product);

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(Purchasedetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setPurchase($this);
        }

        return $this;
    }

    public function removeOrderDetail(Purchasedetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getPurchase() === $this) {
                $orderDetail->setPurchase(null);
            }
        }

        return $this;
    }
}

app-symfony/src/Controller/PurchaseController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Employee;
use App\Entity\Purchase;
use App\Repository\UserRepository;
use App\Repository\PurchaseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PurchaseController extends AbstractController
{
    /**
     * @Route("/purchases", name="purchase_index")
     */
    public function index(PurchaseRepository $purchaseRepo, Request $request, UserRepository $userRepo): Response
    {
        // $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();

        if (!$user) {
            $this->addFlash('danger', "You have to be connected to view your purchases.");
            return $this->redirectToRoute('login');
        }
        /**
         * @var Purchase[] $purchases
         */
        $purchases = [];

        if ($this->isGranted(User::ROLE_CLIENT, $user)) {
            // dd('CLIENT');
            if (is_null($request->get('status'))) {
                $purchases = $purchaseRepo->findBy([
                    'user' => $user,
                ]);
            } else {
                $purchases = $purchaseRepo->findBy([
                    'status' => (int)$request->get('status'),
                    'user' => $user,
                ]);
            }
        }

        if ($this->isGranted(Employee::ROLE_EMPLOYEE, $user)) {
            if (is_null($request->get('status'))) {
                $purchases = $purchaseRepo->findAll();
            } else {
                $purchases = $purchaseRepo->findBy(['status' => (int)$request->get('status')]);
            }
        }

        return $this->render('purchase/index.html.twig', [
            'purchases' => $purchases,
            'statuses' => Purchase::STATUSES,
            'filteredStatus' => $request->get('status') ?? null
        ]);
    }

    /**
     * @Route("/purchases/{id}", name="purchase_details")
     */
    public function details(int $id, PurchaseRepository $purchaseRepo): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $purchase = $purchaseRepo->find($id);

        if (!$purchase) throw $this->createNotFoundException("This purchase doesn't exists !");

        return $this->render('purchase/details.html.twig', [
            'purchase' => $purchase,
            'statuses' => Purchase::STATUSES
        ]);
    }

    /**
     * @Route("/purchases-update-status/{id}", name="purchase_update_status")
     */
    public function updateStatus(int $id, PurchaseRepository $purchaseRepo, Request $request, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if ($this->isGranted(Employee::ROLE_EMPLOYEE, $this->getUser())) {
            $purchase = $purchaseRepo->find($id);

            if (!$purchase) throw $this->createNotFoundException("This purchase doesn't exists !");

            $newStatus = $request->get('status');

            if (is_null($newStatus)) throw new \Exception("The status is mandatory !");

            $purchase->setStatus((int)$newStatus);
            $em->persist($purchase);
            $em->flush();

            $this->addFlash('success', "The status for the purchase #{$purchase->getId()} has passed to : {$purchase->getStatusLabel()}");
            return $this->redirectToRoute('purchase_details', ['id' => $purchase->getId()]);
        }

        $this->addFlash('danger', "You don't have the permission to execute this action.");
        return $this->redirectToRoute('purchase_index');
    }
}

app-symfony/templates/purchase/_productOrderDetail.html.twig
<li class="list-group-item d-flex justify-content-between lh-sm">
	<div>
		<h6 class="my-0">#{{ d.product.id }}
			|
			{{ d.product.name }}</h6>
		<small class="text-muted">Section : {{ d.product.section.name }} <i class="bi bi-arrow-up-right-square"></i> <a href="{{ path('product_detail', {id: d.product.id}) }}">Go to product's page</a></small>
	</div>
	<span class="text-muted">{{ d.product.price | amount }} x {{ d.quantity }} = {{ (d.product.price * d.quantity) | amount }}</span>
</li>

app-symfony/templates/purchase/details.html.twig
{% extends "base.html.twig" %}

{% block body %}
{% set bgColor = ['bg-warning text-dark', 'bg-success', 'bg-secondary'] %}
	<div class="py-5 text-center">
		<h2>Purchase #{{ purchase.id }}</h2>
		<p class="lead">
		{% if purchase.employee %}
			Person in charge : <b>{{ purchase.employee.name }}</b><br/>
		{% endif %}
		Made {{ purchase.dateCreation | date("l d/m/Y", "Europe/Paris") }}
			at
			{{ purchase.dateCreation | date("m:h") }}<br/>
			{% set toPay = purchase.toPay == 0 ? '<span class="badge rounded-pill bg-success">Paid</span>' : ('<span class="badge rounded-pill bg-danger">' ~ purchase.toPay | amount ~ ' left to paid</span>') %}
			{{ toPay | raw }}
			<span class="badge rounded-pill {{ bgColor[purchase.status] }}">{{ purchase.statusLabel | lower | capitalize }}</span>
			</p>
	</div>
	<div class="row g-5">
		<div class="col-md-6 col-lg-6 order-md-last">
			<h4 class="d-flex justify-content-between align-items-center mb-3">
				<span class="text-primary">Purchase's details</span>
				<span class="badge bg-primary rounded-pill">{{ purchase.orderDetails | length }} product{{ (purchase.orderDetails | length) > 1 ? 's' : '' }}</span>
			</h4>
			<ul class="list-group mb-3">
				{% for d in purchase.orderDetails %}
					{% include "purchase/_productOrderDetail.html.twig" with {'d': d} %}
				{% endfor %}
				<li class="list-group-item d-flex justify-content-between">
					<span>Total (EUR)</span>
					<strong>{{ purchase.amount | amount }}</strong>
				</li>
			</ul>
			{% if is_granted('ROLE_EMPLOYEE')  %}
				<form method="POST" action="{{ path('purchase_update_status', { id: purchase.id }) }}">
					<select name="status" class="form-select form-select mb-3" aria-label=".form-select-lg example">
						<option>-- Choose a status --</option>
						{% for key, s in statuses %}
							<option {{ key == purchase.status ? 'selected' : '' }} value="{{ key }}">{{ s | lower | capitalize }}</option>
						{% endfor %}
					</select>
					<button type="submit" class="btn btn-primary">Update status</button>
				</form>
			{% endif %}
		</div>
		<div class="col-md-6 col-lg-6">
			<h4 class="mb-3">Client's information</h4>
			<form class="needs-validation" novalidate="">
				<div class="row g-3">
					<div class="col-sm-12">
						<label for="firstName" class="form-label">Fullname</label>
						<input type="text" class="form-control" id="firstName" value="{{ purchase.user.name }}" disabled>
					</div>
					<div class="col-12">
						<label for="email" class="form-label">Email</label>
						<input type="email" class="form-control" id="email" value="{{ purchase.user.email }}" disabled>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

app-symfony/templates/purchase/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
	{% set bgColor = ['bg-warning text-dark', 'bg-success', 'bg-secondary'] %}
	<ul class="list-inline w-100 text-center">
		<li class="list-inline-item">Filter by status :
		</li>
		<li class="list-inline-item">
			<a class="btn {{ filteredStatus == '' ? 'btn-primary' : 'btn-outline-primary' }}" href="{{ path('purchase_index') }}">All</a>
		</li>
		{% for key, s in statuses %}
			<li class="list-inline-item">
				<form>
					<input name="status" type="hidden" value={{ key }}>
					<button class="btn {{ filteredStatus != '' and filteredStatus == key ? 'btn-primary' : 'btn-outline-primary' }}" type="submit">{{ s }}</button>
				</form>
			</li>
		{% endfor %}
	</ul>

	<div class="list-group">
		{% for p in purchases %}
			<a href="{{ path('purchase_details', {id: p.id}) }}" class="list-group-item list-group-item-action">
				<div class="d-flex w-100 justify-content-between">
					<h5 class="mb-1">Purchase #{{ p.id }}</h5>
					<small class="badge rounded-pill {{ bgColor[p.status] }} d-flex align-items-center">
						Status :
						{{ p.statusLabel | lower | capitalize }}
					</small>
				</div>
				{% set toPay = p.toPay == 0 ? '<span class="badge rounded-pill bg-success">Paid</span>' : ('<span class="badge rounded-pill bg-danger">' ~ p.toPay | amount ~ ' left to paid</span>') %}
				<p class="mb-1 d-flex align-items-center">Amount :
					{{ p.amount | amount }}&nbsp;{{ toPay | raw }}</p>
				<small>
					Made by
					{{ p.user.name }}
					on
					{{ p.dateCreation | date("l d/m/Y", "Europe/Paris") }}
					at
					{{ p.dateCreation | date("m:h") }}
				</small>
			</a>
		{% endfor %}
	</div>
{% endblock %}